version: '3'

services:
  postgresProductos:
    image: postgres:15-alpine
    container_name: ukiyoBD-ms-productos
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - productos_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - ukiyo-network

  ms-productos:
    build:
      context: ../../../
      dockerfile: ./apps/${MICROSERVICIO}/deploy/Dockerfile
      args:
        - MICROSERVICIO=${MICROSERVICIO}
        - CONTEXTO=${CONTEXTO}
    container_name: ukiyo-${MICROSERVICIO}
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - ukiyo-network
    # depends_on:
    #   - postgresProductos

volumes:
  productos_data:

networks:
  ukiyo-network:
    external: true