services:
  api-gateway:
    build:
      context: ../../../
      dockerfile: ./apps/${MICROSERVICIO}/deploy/Dockerfile
      args:
        - MICROSERVICIO=${MICROSERVICIO}
    container_name: ukiyo-${MICROSERVICIO}
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      # Variables para conectar con los ms
      - USUARIOS_HOST=${USUARIOS_HOST}
      - USUARIOS_TCP_PORT=${USUARIOS_TCP_PORT}
      - CLIENTES_HOST=${CLIENTES_HOST}
      - CLIENTES_TCP_PORT=${CLIENTES_TCP_PORT}
      - PRODUCTOS_HOST=${PRODUCTOS_HOST}
      - PRODUCTOS_TCP_PORT=${PRODUCTOS_TCP_PORT}
    networks:
      - ukiyo-network

networks:
  ukiyo-network:
    external: true