version: '3.8'

services:
  api-gateway:
    build:
      context: ${CONTEXT}
      dockerfile: ./apps/${MICROSERVICIO}/deploy/Dockerfile
      args:
        - MICROSERVICIO=${MICROSERVICIO}
    container_name: ukiyo-${MICROSERVICIO}
    ports:
      - "${GATEWAY_PORT}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - GATEWAY_PORT=${GATEWAY_PORT}
      - USUARIOS_HOST=${USUARIOS_HOST}
      - USUARIOS_TCP_PORT=${USUARIOS_TCP_PORT}
      - CLIENTES_HOST=${CLIENTES_HOST}
      - CLIENTES_TCP_PORT=${CLIENTES_TCP_PORT}
      - PRODUCTOS_HOST=${PRODUCTOS_HOST}
      - PRODUCTOS_TCP_PORT=${PRODUCTOS_TCP_PORT}
    networks:
      - ukiyo-network

networks:
  ukiyo-network:
    external: true